### ISSUE TITLE
Add missing maintainers

### ISSUE THREAD

**Issue by flazarus1A** [quarkiverse/quarkus-kafka-streams-processor#40]
The initial extension proposal was made with only a subset of contributors as maintainers.
We need the rest of the team to be able to contribute effectively as well.

@gastaldi would it be possible to add these people as maintainers?

Anna Lazar: @Annlazar
Aymen Fatnassi: @afatnassi1a
Bruno Soares Simoes: @bsoaressimoes 
Christian Semaan: @csemaan1A
Ivan Tchomgue Mieguem: @ivantchomgue1a
Lauriane Douais: @ldouais1a

Thanks in advance!

**Comment by gastaldi** [comment]
@flazarus1A sure, just add them [here](https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-kafka-streams-processor.tf#L32) and submit a PR. Then they will be automatically added to the team

**Comment by flazarus1A** [comment]
Will do, thanks for the quick feedback!

**Comment by gastaldi** [comment]
@flazarus1A note that the PR must come from a branch form that repository, not a fork. 
 See https://github.com/quarkiverse/quarkiverse-devops/tree/main/terraform-scripts#workflow-for-new-repositories

**Comment by flazarus1A** [comment]
Understood, thanks
